name: Deploy Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker rm -f docketest || true
            mkdir -p /home/ubuntu/SimpleWebApp/app
            cd /home/ubuntu/SimpleWebApp/app
            if [ -d ".git" ]; then
              git pull origin main
            else
              git pull || git clone https://github.com/${{ github.repository }} .
            fi
            docker build -t docketest .
            docker run -d -p 80:80 --name docketest docketest
          EOF
