name: Deploy Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo docker rm -f docketest || true
            sudo rm -rf /home/SimpleWebApp/DockerTest
            cd /home/SimpleWebApp
            if [ -d ".git" ]; then
              sudo git clone https://github.com/Faiz5000/DockerTest.git
            else
              sudo git clone https://github.com/Faiz5000/DockerTest.git
            fi
            sudo docker rm -f docketest || true
            sudo docker build -t docketest .
            sudo docker run -d -p 80:80 --name docketest docketest
          EOF
